# Generated by Django 6.0.7 on 2026-07-19 06:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('account_type', models.CharField(choices=[('prs', 'Personal'), ('wk', 'Work'), ('inv', 'Investment'), ('learn', 'Learning'), ('save', 'Saving')], default='prs', max_length=250)),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100000000000), django.core.validators.MaxValueValidator(100000000000)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000000000)])),
                ('goal_type', models.CharField(choices=[('most', 'Spend at most'), ('least', 'Save at least')], default='most', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('months', models.PositiveIntegerField(default=1, help_text='Roughly how many months to reach this, just for display.')),
                ('current_amount', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='main.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000000000)])),
                ('kind', models.CharField(choices=[('dep', 'Deposit'), ('wd', 'Withdraw'), ('tout', 'Transfer out'), ('tin', 'Transfer in')], default='dep', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.account')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
