# Generated by Django 5.2.4 on 2026-07-19 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_account_id_alter_goals_id_alter_transaction_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
        migrations.AlterModelOptions(
            name="goals",
            options={"ordering": ["-months"]},
        ),
        migrations.AlterField(
            model_name="goals",
            name="months",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(-100000000000),
                    django.core.validators.MaxValueValidator(100000000000),
                ]
            ),
        ),
    ]
